### ISSUE TITLE
Question about the scale of MAE and RMSE calculations

### ISSUE THREAD

**Issue by brein0453** [hengruizhang98/DiffPuter#1]
Question about the scale of MAE and RMSE calculations
Hello,

Thank you for sharing your work and code. I have a question regarding the calculation of MAE and RMSE metrics.

From reviewing the code, it seems that the ground truth (GT) values are normalized using z-score, but the predictions are reverted to the original scale before calculating MAE and RMSE. However, I am unsure which scale was used for the metrics reported in your paper.

Could you please clarify whether the MAE and RMSE values reported in the paper were calculated on the normalized scale (z-score) or on the original scale?

Thank you for your time and help.

**Comment by hengruizhang98** [comment]
Thanks for your interest! Both MAE and RMSE are calculated on the normalized one (zero-mean and unit variance).

**Comment by brein0453** [comment]
Thank you for your fast reply and clarification. It was very helpful!
